#!/bin/bash
#
# ci/scripts/release
#
# Script for generating Github release / tag assets
# and managing release notes for a Docker Image pipeline
#

set -eu

if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
  echo >&2 "ci/release_notes.md not found.  Did you forget to write them?"
  exit 1
fi

if [[ -z ${VERSION_FROM} ]]; then
  echo >&2 "VERSION_FROM environment variable not set, or empty.  Did you misconfigure Concourse?"
  exit 2
fi
if [[ ! -f ${VERSION_FROM} ]]; then
  echo >&2 "Version file (${VERSION_FROM}) not found.  Did you misconfigure Concourse?"
  exit 2
fi
VERSION=$(cat ${VERSION_FROM})
if [[ -z ${VERSION} ]]; then
  echo >&2 "Version file (${VERSION_FROM}) was empty.  Did you misconfigure Concourse?"
  exit 2
fi

echo "${VERSION}"                  > ${RELEASE_ROOT}/tag
echo "${RELEASE_NAME} ${VERSION}"  > ${RELEASE_ROOT}/name
cp ${REPO_ROOT}/ci/release_notes.md   ${RELEASE_ROOT}/notes.md

# GIT!
if [[ -z $(git config --global user.email) ]]; then
  git config --global user.email "ci@repulsor.net"
fi
if [[ -z $(git config --global user.name) ]]; then
  git config --global user.name "CIBot"
fi

#(cd ${REPO_ROOT}
# git merge --no-edit master
# git add -A
# git status
# git commit -m "release ${VERSION}")

# so that future steps in the pipeline can push our changes
cp -a ${REPO_ROOT} ${REPO_OUT}
